### ISSUE TITLE
Human-friendly rule names

### ISSUE THREAD

**Issue by ZedThree** [PlasmaFAIR/fortitude#106]
[ruff has discussed this](/astral-sh/ruff/issues/1773) previously, see there for more details. Basically, we should allow e.g. `implicit-typing` as an alternative to `T001` for input, and display  both.

As we currently don't have suppression comments, adding this (hopefully) won't be a massive hardship, it should certainly be pretty easy for output.

Two comments to pay attention to though, in terms of implementation:

- [comment one](/astral-sh/ruff/issues/1773#issuecomment-2163951669)
- [comment two](/astral-sh/ruff/issues/1773#issuecomment-2164799403)

So then the design decision is how do register these names? Easiest option is to convert the violation name to snake/hyphen case, but that doesn't allow for alternatives. Maybe that's the primary name, and alternatives must be registered in the big registration macro

**Comment by LiamPattinson** [comment]
Regarding ways to automatically generate different cases:

I tried playing around with [convert_case](https://docs.rs/convert_case/latest/convert_case/) and [Inflector](https://docs.rs/Inflector/latest/inflector/), both of which can convert from camel-case rule/violation names to kebab-case or title-case. Inflector will also do sentence-case.

The problem is that neither library understands the language, and each will simply draw boundaries where they find capital letters/spaces/hyphens/etc. They get pretty close, but there are some issues, e.g. converting `IOError` to sentence-case results in `Ioerror` instead of `IO error`. It looks like you can define custom patterns with `convert_case`, but I'm not sure if you can make something sophisticated enough to do everything we need automatically.

**Comment by LiamPattinson** [comment]
I just double-checked, and convert_case correctly handles acronyms with kebab-case:

```rust
use convert_case::{Case, Casing};

assert_eq!("io-error", "IOError".to_case(Case::Kebab));
```

That's probably the easiest way to generate the human-readable identifier from the `Violation` name.

**Comment by ZedThree** [comment]
Is this done? Or do we want to leave it open till we cover multiple aliases?
