### ISSUE TITLE
Errors in toml config file are silently ignored

### ISSUE THREAD

**Issue by MatthAlex** [PlasmaFAIR/fortitude#118]
Added the following, one after the other.

```bash
$ grep -B 1 -F "line-length" *.toml
fortitude.toml-[check]
fortitude.toml:line-length = 132
--
fpm.toml-[extra.fortitude.check]
fpm.toml:line-length = 132
```

```bash
(.venv) $ fortitude check app/
...
-- Number of errors: 22

(.venv) $ fortitude check app/ --line-length 132
...
-- Number of errors: 6
```

The command line option is respected, but the files are not.

**Comment by ZedThree** [comment]
Thanks for the bug report @MatthAlex! It looks like we're expecting the setting in the config file to be `line_length` with an underscore, but we're not raising an error on unknown variables in the file.

We should probably use `line-length` for consistency with the CLI, and definitely error on unknown settings.

**Comment by MatthAlex** [comment]
Yup, that works, confirmed!

Having it be `line-length` also matches the README example.

**Comment by LiamPattinson** [comment]
Thanks @MatthAlex, I spotted this one myself in https://github.com/PlasmaFAIR/fortitude/issues/247 and patched it in https://github.com/PlasmaFAIR/fortitude/pull/251. The latest commit on main should include the fix, but we haven't released a patch version yet.

@ZedThree Do you think we should make a new release for v0.6.3 now? If so, we should probably also update the file counting issue so that the reported number of files scanned is correct even when the error diagnostics are switched off. I'm a bit concerned that we've made a few too many other changes to `main`, so pushing through to v0.7 might be preferable instead.
