### ISSUE TITLE
Output to SARIF format

### ISSUE THREAD

**Issue by imciner2** [PlasmaFAIR/fortitude#172]
The SARIF format (https://sarifweb.azurewebsites.net/) is a standard schema for JSON that is written and read by many different static analysis  tools (https://github.com/oasis-tcs/sarif-spec/wiki/Known-Producers-and-Consumers#known-producers-of-sarif). For instance, it is written by the GCC and Clang static analyzers, and GitHub CodeQL, and it can be read by IDE extensions (e.g. [VSCode](https://marketplace.visualstudio.com/items?itemName=MS-SarifVSCode.sarif-viewer)) and also git forges (e.g., [GitHub Security](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning), [Azure DevOps](https://docs.kics.io/latest/integrations_azurepipelines/), and there is a request for integration into [GitLab](https://gitlab.com/gitlab-org/gitlab/-/issues/452042)). My use-case would primarily be the git forge integration, so that I can eventually include fortitude in a pipeline and have it scan PRs for issues.

It appears there is a Rust library that wrap the structure already - [serde-sarif](https://docs.rs/serde-sarif/latest/serde_sarif/index.html), so there shouldn't be a need to actually write the JSON formatter for this if we can include this dependency.

**Comment by ZedThree** [comment]
This is actually already on our to-do list! :smile: Because we've built a bunch of fortitude on top of ruff, we're able to mostly reuse their output formatters too. We should be able to mostly copy-paste their [SARIF formatter](https://github.com/astral-sh/ruff/blob/main/crates/ruff_linter/src/message/sarif.rs), as well as their GitHub and Gitlab ones too. It looks like the serde-sarif crate might be even more straightforward too.

PRs definitely welcome if you're interested in contributing!
