### ISSUE TITLE
`Violation` should have `start` and `end`

### ISSUE THREAD

**Issue by ZedThree** [PlasmaFAIR/fortitude#44]
Rather than:

```rust
pub enum ViolationPosition {
    None,
    Line(usize),
    LineCol((usize, usize)),
}
```

which just points to a specific place in the source, having a start and end allows pointing to exactly the offending piece of code and underlining the relevant part(s)

I'm not sure what `None` is supposed to represent here, but it could be encoded as `(0, 0)`. Similarly, `Line` could be the start & end of the whole line.

It would also be most useful if this was in terms of offset into the file, with some conversion utility between offset and line/column numbers. (This is at least partly what all that extra structure is for in ruff)

**Comment by LiamPattinson** [comment]
Great idea, I think this would be necessary first step towards Issue https://github.com/PlasmaFAIR/fortitude/issues/14.

For AST rules, we could make use of [`tree_sitter::Range`](https://docs.rs/tree-sitter/latest/tree_sitter/struct.Range.html) to get the byte-range and row/col-range of any offending nodes (`node.range()` to build it, or `node.byte_range()` if we only need the bytes). I think that should be enough to use with [annotate_snippets](https://docs.rs/annotate-snippets/latest/annotate_snippets/) to automate the diagnostic generation.

As for what the current enum is doing:

`None` is used only by rules that operate on the file path, but since line numbers/columns are 1-indexed you're right that a position of 0 could be interpreted the same way.

I was using `Line(usize)` for regex-based rules, as I wasn't sure how to get the column number of anything that matched. If we can get that, one option to gather info for annotate_snippets would be to simply accumulate the offset into the file as we parse each line.

**Comment by ZedThree** [comment]
> For AST rules, we could make use of [`tree_sitter::Range`](https://docs.rs/tree-sitter/latest/tree_sitter/struct.Range.html) to get the byte-range and row/col-range of any offending nodes (`node.range()` to build it, or `node.byte_range()` if we only need the bytes). I think that should be enough to use with [annotate_snippets](https://docs.rs/annotate-snippets/latest/annotate_snippets/) to automate the diagnostic generation.

Not quite as simple as that, as the tree-sitter range will be the offset into the file, and we'll need the offset into the context snippet -- so subtracting the total length upto the previous two lines or something.

> `None` is used only by rules that operate on the file path, but since line numbers/columns are 1-indexed you're right that a position of 0 could be interpreted the same way.

Ah, I see there's a rule for checking the extension -- maybe `None` should be kept for that case then (or we could do something fancy and display the filename and put the warning caret at the file extension).

> I was using `Line(usize)` for regex-based rules, as I wasn't sure how to get the column number of anything that matched.

https://docs.rs/regex/latest/regex/struct.Match.html#method.range gives the range of the match.

> If we can get that, one option to gather info for annotate_snippets would be to simply accumulate the offset into the file as we parse each line.

Probably better to keep it separate and precompute it

**Comment by ZedThree** [comment]
`ASTRule`s already have the information for start and end, both in terms of offsets and line & column. `TextRule`s can pretty easily have start end line & column, but offsets are a little harder, but maybe not immediately needed.

However, the difficulty in just switching to use:

```
pub enum ViolationPosition {
    None,
    Range(tree_sitter::Range),
}
```

is that _all_ of the tests need updating, and we also need the start/end offsets of every single violation.

In order to not make that a right pain, I suggest the first thing we need to do is to get the equivalent of ruff's `SourceCode` that stores the text and a `LineIndex` that maps lines to offsets. That would make it much easier to update (and expand) the tests. It would also give us a mechanism to convert regex matches to `Range`s.

We'd mostly likely want to convert `TextSize` to plain `usize`, and maybe `TextRange` to `tree_sitter::Range`.
