### ISSUE TITLE
Returning multiple violations from the same rule

### ISSUE THREAD

**Issue by ZedThree** [PlasmaFAIR/fortitude#48]
For example, when checking for missing `intent`s we need to find variable declarations with identifiers in the procedure's parameter list, and then check for the missing attribute. This means it's probably more sensible to collect all such violations for a given procedure at the same time.

Two suggestions:

1. Add a new rule trait that returns a `Vec` of violations, and `append` to the current list
2. Something like ruff's structure, with a `checker` object that's passed into each rule, which can then modify it as appropriate

**Comment by LiamPattinson** [comment]
In an earlier build, when each AST rule would parse the whole tree searching for a given pattern, I had those rules return a `Vec<Violation>` instead of `Option<Violation>`. Having switched it around so that tree is just parsed once and rules are activated depending on their 'entry points', I figured there would be no need to return multiple violations, as each node could only break a rule once.

However, I think you make a good case for switching back to `Vec<Violation>` in this case, as the node we would have to activate the rule on here would be 'identifier', meaning it would trigger on every element in a parameter list and then trigger again for each variable declaration. The algorithm would have to be something like:

- Activate on an 'identifier' node.
- Check that the parent node is function/subroutine parameter list. If not, exit early.
- Search variable declarations in the encapsulating function/subroutine until finding one that matches.
- Check that the corresponding variable declaration has an explicit intent.

It would be simpler to do this instead:

- Activate on the parameter list node.
- For parameters in the list, find matching variable declarations and check for explicit intent. 

I'd prefer not to introduce a new rule trait, as I can't imagine it would be any different to the current `ASTRule` trait beyond returning a `Vec` instead of an `Option`, and it would complicate other bits of the code to accommodate both variants separately. Modifying the existing `ASTRule` trait would be simpler. The only real downside I can think of is that most AST rules will only return one or zero violations, and it feels more 'rusty' to use `Option` in those cases than to return a data structure that might be empty.

**Comment by ZedThree** [comment]
I don't think returning an empty vector is necessarily a bad thing, however we wouldn't be able to use the question mark operator to early return when a TS call returns `None`, so this might make rules a lot more verbose.

We _could_ return `Option<Vec<Violation>>` -- maybe that's fine?

**Comment by ZedThree** [comment]
`Option<Vec<Violation>>` looks workable: https://github.com/PlasmaFAIR/fortitude/commit/42ec05d485f9a8f8f11a796dd9aabb7bd1347374

**Comment by LiamPattinson** [comment]
Good point about using `?` for early exits, and I'm glad to see that the `apply` function and tests only require minimal changes to work after the modification.

Having to write `Some(vec![Violation::from_node(...)])` everywhere feels a little cluttered, and it makes me a little uncomfortable to have both `None` and `Some(vec![])` as equivalent ways to indicate 'no issues found', but I'm struggling to think of a better way to handle it (maybe just a new macro that does the job of `Some(vec![...])` and requires at least one argument?)
